services:
  postgres:
    image: postgres:15
    container_name: payload-postgres
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pg.sh:/docker-entrypoint-initdb.d/init-pg.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payload -d payload"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
